name = "resumelm"
main = ".open-next/worker.js"
compatibility_date = "2026-05-01"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "resumelm-db"
database_id = "43cfc652-228a-4479-902e-f18d95a6be08"

[[kv_namespaces]]
binding = "CACHE"
id = "fa724e80609746ec871d73df271b6a04"

# Uncomment when R2 bucket is created
# [[r2_buckets]]
# binding = "STORAGE"
# bucket_name = "resumelm-files"

[ai]
binding = "AI"
