import { Question } from './types';

export const ONBOARDING_QUESTIONS: Question[] = [
  // --- Personal Info (questions 1-8) ---
  {
    id: 'first_name',
    section: 'personal',
    question: "What's your first name?",
    coachingNote: "Let's start simple. This is how your name will appear at the top of every CV you create.",
    type: 'text',
    placeholder: 'e.g. Alex',
    prefillFrom: 'first_name',
    required: true,
  },
  {
    id: 'last_name',
    section: 'personal',
    question: "And your last name?",
    type: 'text',
    placeholder: 'e.g. Johnson',
    prefillFrom: 'last_name',
    required: true,
  },
  {
    id: 'email',
    section: 'personal',
    question: "What's the best email to reach you?",
    coachingNote: "Use a professional email address. Recruiters notice — firstname.lastname@gmail.com beats xXgamer99Xx@hotmail.com.",
    type: 'text',
    placeholder: 'e.g. alex@example.com',
    prefillFrom: 'email',
    required: true,
  },
  {
    id: 'phone_number',
    section: 'personal',
    question: "Your phone number?",
    coachingNote: "Include country code if you're applying internationally. Most ATS systems parse phone numbers, so keep the format clean.",
    type: 'text',
    placeholder: 'e.g. +1 (555) 123-4567',
    prefillFrom: 'phone_number',
  },
  {
    id: 'location',
    section: 'personal',
    question: "Where are you based?",
    coachingNote: "City and country is enough. Full addresses are outdated — and a privacy risk. Many companies filter by location, so this matters for remote roles too.",
    type: 'text',
    placeholder: 'e.g. San Francisco, CA',
    prefillFrom: 'location',
  },
  {
    id: 'website',
    section: 'personal',
    question: "Do you have a personal website or portfolio?",
    coachingNote: "A portfolio link can set you apart. If you don't have one yet, no worries — skip for now.",
    type: 'text',
    placeholder: 'e.g. https://alexjohnson.dev',
    prefillFrom: 'website',
  },
  {
    id: 'linkedin_url',
    section: 'personal',
    question: "What's your LinkedIn URL?",
    coachingNote: "Did you know? 87% of recruiters use LinkedIn to evaluate candidates. Make sure your profile URL is customized (linkedin.com/in/yourname), not the default random string.",
    type: 'text',
    placeholder: 'e.g. https://linkedin.com/in/alexjohnson',
    prefillFrom: 'linkedin_url',
  },
  {
    id: 'github_url',
    section: 'personal',
    question: "GitHub profile? (if applicable)",
    coachingNote: "For tech roles, an active GitHub profile with pinned projects can be as valuable as a cover letter.",
    type: 'text',
    placeholder: 'e.g. https://github.com/alexjohnson',
    prefillFrom: 'github_url',
  },

  // --- Experience (questions 9-14) ---
  {
    id: 'experience_intro',
    section: 'experience',
    question: "Let's talk about your work experience.",
    coachingNote: "Here's something most people don't know: 75% of resumes get filtered by ATS (Applicant Tracking Systems) before a human ever sees them. The way you describe your experience matters more than you think. We've already pulled what we could from your CV — let's make sure it's complete and ATS-ready.",
    type: 'textarea',
    placeholder: "We've pre-filled your experience from your CV. Review it, add anything missing, or tell us about roles we might have missed...",
    prefillFrom: 'work_experience_summary',
  },
  {
    id: 'proudest_achievement',
    section: 'experience',
    question: "What's your proudest professional achievement?",
    coachingNote: "Strong resumes lead with impact, not duties. Think: 'Increased revenue by 40%' not 'Responsible for sales'. Numbers are your best friend on a resume — they're the first thing both ATS and humans scan for.",
    type: 'textarea',
    placeholder: "e.g. Led a team of 5 to rebuild our payment system, reducing transaction failures by 60% and saving $2M annually...",
  },
  {
    id: 'work_style',
    section: 'experience',
    question: "How would you describe your working style?",
    coachingNote: "This helps us frame your experience in the right light. A collaborative leader tells a different story than an independent problem-solver — both are valuable.",
    type: 'select',
    options: ['Independent contributor', 'Team collaborator', 'Team lead / manager', 'Cross-functional coordinator', 'A mix of these'],
  },
  {
    id: 'industries',
    section: 'experience',
    question: "What industries have you worked in?",
    coachingNote: "Industry experience is a strong signal for recruiters. If you're switching industries, we'll make sure your transferable skills shine through.",
    type: 'tags',
    placeholder: 'Type an industry and press Enter...',
    prefillFrom: 'industries',
  },
  {
    id: 'years_experience',
    section: 'experience',
    question: "Roughly how many years of professional experience do you have?",
    type: 'select',
    options: ['Less than 1 year', '1-3 years', '3-5 years', '5-10 years', '10+ years'],
  },
  {
    id: 'management_experience',
    section: 'experience',
    question: "Have you managed people or teams?",
    coachingNote: "Even informal leadership counts — mentoring interns, leading a project team, or coordinating across departments. Don't sell yourself short.",
    type: 'select',
    options: ['No management experience yet', 'Informal/project leadership', 'Managed 1-5 people', 'Managed 5-15 people', 'Managed 15+ people'],
  },

  // --- Education (questions 15-19) ---
  {
    id: 'education_intro',
    section: 'education',
    question: "Now let's cover your education.",
    coachingNote: "Fun fact: for experienced professionals (5+ years), education typically goes at the bottom of your resume. For recent grads, it goes near the top. We'll position it perfectly.",
    type: 'textarea',
    placeholder: "We've pre-filled your education from your CV. Review it and add any missing degrees, certifications, or courses...",
    prefillFrom: 'education_summary',
  },
  {
    id: 'certifications',
    section: 'education',
    question: "Do you have any professional certifications?",
    coachingNote: "Certifications like AWS, PMP, CPA, or Google Analytics are ATS gold — they're exact keyword matches that algorithms love.",
    type: 'tags',
    placeholder: 'Type a certification and press Enter...',
  },
  {
    id: 'courses',
    section: 'education',
    question: "Any relevant online courses or bootcamps?",
    coachingNote: "Online learning absolutely counts. Coursera, Udemy, bootcamps — list them. They show initiative and a growth mindset.",
    type: 'tags',
    placeholder: 'Type a course name and press Enter...',
  },
  {
    id: 'languages',
    section: 'education',
    question: "What languages do you speak?",
    coachingNote: "Multilingual? That's a competitive advantage. Even basic proficiency is worth mentioning for international companies.",
    type: 'tags',
    placeholder: 'e.g. English (Native), Spanish (Conversational)...',
  },
  {
    id: 'gpa_honors',
    section: 'education',
    question: "Any academic honors, high GPA, or awards worth highlighting?",
    coachingNote: "Rule of thumb: include GPA if it's 3.5+ and you graduated within the last 3 years. For everyone else, awards and honors carry more weight.",
    type: 'textarea',
    placeholder: "e.g. Dean's List 4 semesters, GPA 3.8, Phi Beta Kappa...",
  },

  // --- Skills (questions 20-25) ---
  {
    id: 'skills_intro',
    section: 'skills',
    question: "Time for skills! What are your strongest technical skills?",
    coachingNote: "Pro tip: the Skills section is where ATS does the heaviest matching. Be specific — 'Python' is better than 'programming', and 'React, Next.js, TypeScript' is better than 'web development'.",
    type: 'textarea',
    placeholder: "We've pre-filled your skills from your CV. Add any we missed...",
    prefillFrom: 'skills_summary',
  },
  {
    id: 'tools_software',
    section: 'skills',
    question: "What tools and software do you use regularly?",
    coachingNote: "Include everything: Figma, Jira, Salesforce, Excel, Slack, Notion — tools show you can hit the ground running. Many job descriptions list specific tools as requirements.",
    type: 'tags',
    placeholder: 'Type a tool name and press Enter...',
  },
  {
    id: 'soft_skills',
    section: 'skills',
    question: "What soft skills do your colleagues value most about you?",
    coachingNote: "Soft skills matter more than ever. But instead of listing 'team player' (everyone does), we'll weave these into your experience descriptions where they'll actually be believed.",
    type: 'select',
    options: ['Communication & presentation', 'Problem solving & critical thinking', 'Leadership & mentoring', 'Adaptability & learning agility', 'Collaboration & teamwork'],
  },
  {
    id: 'skill_level',
    section: 'skills',
    question: "How do you stay current in your field?",
    coachingNote: "Continuous learning signals are powerful. Mentioning specific conferences, publications, or communities shows you're engaged with your industry.",
    type: 'textarea',
    placeholder: 'e.g. I read Hacker News daily, attend React conferences, contribute to open source...',
  },
  {
    id: 'frameworks',
    section: 'skills',
    question: "Any specific frameworks, methodologies, or standards you work with?",
    coachingNote: "Agile, Scrum, Six Sigma, ISO standards, HIPAA compliance — these are keyword magnets for ATS. Don't forget them.",
    type: 'tags',
    placeholder: 'e.g. Agile, Scrum, CI/CD, REST, GraphQL...',
  },
  {
    id: 'programming_languages',
    section: 'skills',
    question: "Which programming languages are you most proficient in? (if applicable)",
    type: 'tags',
    placeholder: 'e.g. JavaScript, Python, Go, Rust...',
    prefillFrom: 'programming_languages',
  },

  // --- Projects (questions 26-30) ---
  {
    id: 'projects_intro',
    section: 'projects',
    question: "Let's talk about your projects.",
    coachingNote: "Projects show what you can build, not just what you've been assigned. Side projects, open source contributions, hackathon wins — they all count. For career changers, projects can be more powerful than work experience.",
    type: 'textarea',
    placeholder: "We've pre-filled your projects from your CV. Add any side projects, open source work, or portfolio pieces...",
    prefillFrom: 'projects_summary',
  },
  {
    id: 'project_impact',
    section: 'projects',
    question: "Which project are you most proud of and why?",
    coachingNote: "The best project descriptions follow this formula: What you built + What tech you used + What impact it had. 'Built a real-time dashboard using React and D3.js that reduced reporting time by 80%' is chef's kiss.",
    type: 'textarea',
    placeholder: 'Tell us about a project that showcases your best work...',
  },
  {
    id: 'open_source',
    section: 'projects',
    question: "Any open source contributions?",
    coachingNote: "Even small PRs count. Contributing to well-known projects signals you can work in collaborative codebases and follow established standards.",
    type: 'textarea',
    placeholder: 'e.g. Contributed to React Native, maintained a popular npm package with 1k+ stars...',
  },
  {
    id: 'publications',
    section: 'projects',
    question: "Have you published any articles, papers, or given talks?",
    coachingNote: "Thought leadership sets you apart from other candidates. Blog posts, conference talks, research papers — they all demonstrate deep expertise.",
    type: 'textarea',
    placeholder: 'e.g. Published on Medium about microservices architecture, spoke at PyCon 2024...',
  },
  {
    id: 'volunteer_work',
    section: 'projects',
    question: "Any volunteer work or community involvement related to your field?",
    coachingNote: "Mentoring at coding bootcamps, organizing meetups, volunteering tech skills at nonprofits — these show character and create networking opportunities.",
    type: 'textarea',
    placeholder: 'e.g. Mentor at Code for America, organize local Python meetup...',
  },

  // --- Goals (questions 31-35) ---
  {
    id: 'target_role',
    section: 'goals',
    question: "What role are you targeting?",
    coachingNote: "Be specific. 'Senior Frontend Engineer' is better than 'software developer'. The more targeted your Master CV, the better our tailoring will work.",
    type: 'text',
    placeholder: 'e.g. Senior Frontend Engineer, Product Manager, Data Scientist...',
    required: true,
  },
  {
    id: 'target_companies',
    section: 'goals',
    question: "What types of companies interest you?",
    coachingNote: "Startup vs. enterprise requires different resume framing. A startup wants to see versatility and ownership; an enterprise wants depth and process.",
    type: 'select',
    options: ['Early-stage startups', 'Growth-stage companies', 'Large enterprises', 'FAANG / Big Tech', 'No strong preference'],
  },
  {
    id: 'salary_expectations',
    section: 'goals',
    question: "What's your expected compensation range? (optional, private)",
    coachingNote: "This stays private — we never put salary on your CV. But knowing your range helps us understand your seniority level for better positioning.",
    type: 'text',
    placeholder: 'e.g. $120k-$150k, or skip this',
  },
  {
    id: 'work_preference',
    section: 'goals',
    question: "What's your preferred work arrangement?",
    type: 'select',
    options: ['Fully remote', 'Hybrid', 'On-site', 'Open to all'],
  },
  {
    id: 'anything_else',
    section: 'goals',
    question: "Anything else you want us to know?",
    coachingNote: "This is your space. Career gaps you want to address? A unique angle that doesn't fit neatly into categories? Special circumstances? Tell us everything — we'll figure out the best way to present it.",
    type: 'textarea',
    placeholder: "Anything that might help us build a better CV for you...",
  },
];

export const SECTION_TITLES: Record<string, string> = {
  personal: 'Personal Information',
  experience: 'Work Experience',
  education: 'Education',
  skills: 'Skills & Tools',
  projects: 'Projects & Contributions',
  goals: 'Career Goals',
};
